import type { AppState, Evidence, TrainingSessionRun } from '../../domain/types';
import type { TrainingSessionDefinition, SessionBlock } from '../../content/trainingTypes';
import { canExecutePhysicalBlock } from './trainingGuards';

function evidence(state:AppState,session:TrainingSessionDefinition,blockIndex:number,kind:'COMPLETION'|'REFLECTION'='COMPLETION'):AppState{const e:Evidence={id:crypto.randomUUID(),lessonId:session.id,stage:'PRACTICE',kind,value:String(blockIndex),createdAt:new Date().toISOString()};return{...state,evidence:[...state.evidence,e]};}
function current(state:AppState,session:TrainingSessionDefinition):SessionBlock|undefined{return session.blocks[state.trainingRun?.currentBlockIndex??0];}
export function startTraining(state:AppState,session:TrainingSessionDefinition):AppState{if(state.trainingRun?.sessionId===session.id)return state;return{...state,trainingRun:{sessionId:session.id,sessionVersion:session.version,status:'READY',currentBlockIndex:0,currentRound:1,completedReps:0,evidenceIds:[]}};}
export function startBlock(state:AppState,session:TrainingSessionDefinition):AppState{const run=state.trainingRun;if(!run)return startTraining(state,session);const block=current(state,session);if(block?.type==='DRILL'){const drillId=block.drillId; if(!canExecutePhysicalBlock(state)){return{...state,trainingRun:{...run,status:'STOPPED'}};} void drillId;} return{...state,trainingRun:{...run,status:'RUNNING'}};}
export function completeRepetition(state:AppState,session:TrainingSessionDefinition):AppState{const run=state.trainingRun;const block=current(state,session);if(!run||!block||block.type!=='DRILL'||!canExecutePhysicalBlock(state)||run.status==='STOPPED'||run.status==='COMPLETED')return state;const next={...state,trainingRun:{...run,status:'RUNNING',completedReps:run.completedReps+1}};return next;}
export function completeTrainingBlock(state:AppState,session:TrainingSessionDefinition):AppState{const run=state.trainingRun;const block=current(state,session);if(!run||!block||run.status==='STOPPED'||run.status==='COMPLETED')return state;if(block.type==='DRILL'&&!canExecutePhysicalBlock(state))return state;const already=run.evidenceIds.includes(String(run.currentBlockIndex));if(already)return state;const withEvidence=evidence(state,session,run.currentBlockIndex,block.type==='CHECK_IN'?'REFLECTION':'COMPLETION');const e=withEvidence.evidence.at(-1)!;const nextIndex=run.currentBlockIndex+1;const done=nextIndex>=session.blocks.length;return{...withEvidence,trainingRun:{...run,currentBlockIndex:nextIndex,completedReps:0,status:done?'COMPLETED':'READY',evidenceIds:[...run.evidenceIds,e.id]}};}
export function pauseTraining(state:AppState):AppState{return state.trainingRun?.status==='RUNNING'?{...state,trainingRun:{...state.trainingRun,status:'PAUSED'}}:state;}
export function resumeTraining(state:AppState):AppState{return state.trainingRun?.status==='PAUSED'?{...state,trainingRun:{...state.trainingRun,status:'RUNNING'}}:state;}
export function stopTraining(state:AppState):AppState{return state.trainingRun&&['RUNNING','PAUSED','READY'].includes(state.trainingRun.status)?{...state,trainingRun:{...state.trainingRun,status:'STOPPED'}}:state;}
export function tick(state:AppState,session:TrainingSessionDefinition,seconds:number):AppState{const run=state.trainingRun;const block=current(state,session);if(!run||run.status!=='RUNNING'||!block||block.type!=='REST')return state;const remaining=Math.max(0,(run.remainingSeconds??block.seconds)-Math.max(0,seconds));return{...state,trainingRun:{...run,remainingSeconds:remaining}};}
