import React,{useEffect}from'react';
import type{AppState}from'../../domain/types';
import{fundamentos01,drills,techniques}from'../../content/fundamentalTrainingPack';
import{completeRepetition,completeTrainingBlock,pauseTraining,resumeTraining,startBlock,startTraining,stopTraining,tick}from'./trainingEngine';
import{getTrainingGuidance}from'./trainingGuards';
export function TrainingPlayer({state,onChange,onDone}:{state:AppState;onChange:(s:AppState)=>void;onDone:()=>void}){
 const run=state.trainingRun??startTraining(state,fundamentos01);const block=fundamentos01.blocks[run.currentBlockIndex];const drill=block?.type==='DRILL'?drills.find(d=>d.id===block.drillId):undefined;const technique=drill?.techniqueIds.map(id=>techniques.find(t=>t.id===id)).find(Boolean);const guidance=getTrainingGuidance(state);
 useEffect(()=>{if(run.status!=='RUNNING')return;const timed=block?.type==='REST'||(block?.type==='DRILL'&&drill?.mode==='TIMED');if(!timed)return;const id=window.setInterval(()=>onChange(tick(state,fundamentos01,1)),1000);return()=>window.clearInterval(id)},[run.status,run.currentBlockIndex,run.remainingSeconds,block,drill,onChange]);
 if(!block||run.status==='COMPLETED')return null;
 const start=()=>onChange(startBlock(state,fundamentos01));const advance=()=>{const next=completeTrainingBlock(state,fundamentos01);onChange(next);if(next.trainingRun?.status==='COMPLETED')onDone()};const timed=block.type==='REST'||(block.type==='DRILL'&&drill?.mode==='TIMED');const shownTime=run.remainingSeconds??(block.type==='REST'?block.seconds:drill?.target);
 return <section className="panel flow"><p className="eyebrow">FUNDAMENTOS 01 · {run.currentBlockIndex+1}/{fundamentos01.blocks.length}</p><h1>{block.type==='DRILL'?drill?.title:block.type==='REST'?'Descanso':block.type==='CHECK_IN'?'Check-in':block.title}</h1><p className="lead">{block.type==='INSTRUCTION'?block.text:block.type==='CHECK_IN'?block.prompt:technique?.checkpoints.join(' · ')||'Siga os checkpoints com controle.'}</p>{guidance==='REDUCED'&&<p className="notice">Intensidade reduzida: mantenha o movimento confortável e controlado.</p>}{guidance==='PAUSED'&&block.type==='DRILL'&&<p className="notice">Execução física pausada pela prontidão atual.</p>}{block.type==='DRILL'&&drill?.mode==='REPS'&&<div className="dashboard-card"><small>REPETIÇÕES</small><strong>{run.completedReps}/{drill.target}</strong></div>}{timed&&<div className="dashboard-card"><small>TEMPO</small><strong>{shownTime}s</strong></div>}<div className="choice">{block.type==='DRILL'&&drill?.mode==='REPS'&&<button className="primary" onClick={()=>onChange(completeRepetition(state,fundamentos01))}>Registrar repetição</button>}<button onClick={start}>Iniciar bloco</button>{run.status==='RUNNING'&&<button onClick={()=>onChange(pauseTraining(state))}>Pausar</button>}{run.status==='PAUSED'&&<button onClick={()=>onChange(resumeTraining(state))}>Retomar</button>}<button onClick={()=>onChange(stopTraining(state))}>Parar</button><button onClick={advance}>Concluir bloco</button></div></section>;
}
